name: Build Magisk S27

on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Init submodules
        run: |
         git submodule sync --recursive
         git submodule update --init --recursive

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: "21"

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Setup Android SDK
        uses: android-actions/setup-android@v3

      - name: Install Dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            git \
            zip \
            unzip \
            curl \
            wget \
            clang \
            lld \
            cmake \
            ninja-build \
            ccache

      - name: Accept Android Licenses
        run: yes | sdkmanager --licenses

      - name: Install Magisk NDK
        run: |
          python3 build.py ndk

      - name: Build
        run: |
          python3 build.py all

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: Magisk-APK
          path: out/app-release.apk
          if-no-files-found: warn

      - name: Upload Outputs
        uses: actions/upload-artifact@v4
        with:
          name: Magisk-Out
          path: out/**
          if-no-files-found: warn
